serenity.project.name=EventHub API Automation
# Where Serenity generates reports
serenity.outputDirectory=target/site/serenity

# Logging
serenity.logging=NORMAL

# Report encoding
serenity.report.encoding=UTF-8

# Show detailed step information
serenity.reports.show.step.details=false

# JSON formatting
json.pretty.printing=true

# Console output
serenity.console.colors=true

# Keep stack traces readable
simplified.stack.traces=true

# Output formats
output.formats=json,xml